"""empty message

Revision ID: 640758127ec4
Revises: a216d772cf4b
Create Date: 2025-09-18 21:20:34.996128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640758127ec4'
down_revision = 'a216d772cf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seeking_talent', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('seeking_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('seeking_description')
        batch_op.drop_column('seeking_talent')

    # ### end Alembic commands ###
