"""refactor(models): simplify PostalCode model for US-only forms

Revision ID: a216d772cf4b
Revises: 4c230c87191f
Create Date: 2025-09-18 20:09:15.443800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a216d772cf4b'
down_revision = '4c230c87191f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('postal_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_country_code'), type_='unique')
        batch_op.create_unique_constraint('uq_city_state', ['city', 'state'])
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postal_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_city_state', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_country_code'), ['country', 'code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###
