"""empty message

Revision ID: d809cff94cc8
Revises: cd161eeb0293
Create Date: 2025-09-24 14:19:18.801706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd809cff94cc8'
down_revision = 'cd161eeb0293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist_links', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_artistid_linkid', ['artist_id', 'link_id'])

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('venue_links', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_venueid_linkid', ['venue_id', 'link_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venue_links', schema=None) as batch_op:
        batch_op.drop_constraint('uq_venueid_linkid', type_='unique')

    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    with op.batch_alter_table('artist_links', schema=None) as batch_op:
        batch_op.drop_constraint('uq_artistid_linkid', type_='unique')

    # ### end Alembic commands ###
